sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t praviola/docker-react -f Dockerfile.dev .

script:
  - docker run praviola/docker-react npm run test -- --coverage
